# Generated by Django 5.2.11 on 2026-09-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_room_approvers_alter_booking_id_alter_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(help_text='MOET ICT Conference Room', max_length=100),
        ),
    ]
