# Generated by Django 5.2.11 on 2026-09-30 05:20

import bookings.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.operations
from django.conf import settings
from django.db import migrations, models


def validate_no_active_overlaps(apps, schema_editor):
    Booking = apps.get_model('bookings', 'Booking')
    active_bookings = Booking.objects.filter(
        status__in=['Pending', 'Approved']
    ).order_by('room_id', 'start_time', 'end_time')

    current_room_id = None
    latest_end_time = None
    for booking in active_bookings:
        if booking.room_id != current_room_id:
            current_room_id = booking.room_id
            latest_end_time = None
        if latest_end_time and booking.start_time < latest_end_time:
            raise RuntimeError(
                'Cannot add booking conflict protection because active bookings overlap '
                f'in room ID {booking.room_id}. Resolve the conflict and run migrate again.'
            )
        if latest_end_time is None or booking.end_time > latest_end_time:
            latest_end_time = booking.end_time


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_cancellation_reason_booking_cancelled_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        django.contrib.postgres.operations.BtreeGistExtension(),
        migrations.RunPython(validate_no_active_overlaps, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='booking_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['Pending', 'Approved'])), expressions=[(bookings.models.TsTzRange('start_time', 'end_time', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), ('room', '=')], name='exclude_overlapping_active_room_bookings', violation_error_message='Sorry, this room is already booked during this time.'),
        ),
    ]
