# Generated by Django 5.2.11 on 2026-09-30 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_booking_end_after_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('requested', 'Request submitted'), ('updated', 'Booking updated'), ('approved', 'Booking approved'), ('rejected', 'Booking rejected'), ('cancelled', 'Booking cancelled')], max_length=20)),
                ('recipient', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=150)),
                ('action_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bookings.booking')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
