# Generated by Django 5.2.11 on 2026-09-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_bookingnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional public image URL for the room card'),
        ),
    ]
