# Generated by Django 5.2.11 on 2026-10-01 01:09

import bookings.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_room_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a JPG, PNG, or WebP image (up to 5 MB).', upload_to='rooms/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), bookings.models.validate_room_image_size]),
        ),
        migrations.AlterField(
            model_name='room',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional external image URL, used only when no image is uploaded.'),
        ),
    ]
